
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicalQRWebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MedicalReceipt
{

    public System.Guid id { get; set; }

    public System.DateTime scanDate { get; set; }

    public string validationResult { get; set; }

    public System.Guid pharmacyId { get; set; }

    public string uicId { get; set; }

    public string securityCodeId { get; set; }

    public string applicationMessage { get; set; }



    public virtual Pharmacy Pharmacy { get; set; }

}

}
