
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicalQRWebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Pharmacy
{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy()
        {
            this.MedicalReceipts = new HashSet<MedicalReceipt>();
        }
    
        public System.Guid id { get; set; }
        public string cuit { get; set; }
        public string company_name { get; set; }
        public string business_name { get; set; }
        public string email { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string GmailID { get; set; }
        public string FacebookID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalReceipt> MedicalReceipts { get; set; }
    }
}
