//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalQRWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityCode
    {
        public System.Guid id { get; set; }
        public int securityNumber { get; set; }
        public System.DateTime expirationDate { get; set; }
        public System.Guid doctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
